baseURL = "http://example.org/"
languageCode = "en-us"
title = "Robin ke kaagzad"
theme = "hugo-theme-learn"
[params]
    disableSearch = true
    landingPageURL = "/"
    themeVariant = "green"
[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "monokai"
        tabWidth = 4