baseURL = ""
languageCode = "en-us"
title = "Robin ke kaagzad"
theme = "hugo-theme-learn"
[params]
    author = "Robin Siwach"
    disableSearch = false
    disableLandingPage = false
    landingPageURL = "/"
    landingPageName = "<i class='fas fa-home'></i> Home"
    themeVariant = "green"
[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "monokai"
        tabWidth = 4